// This is a temporary file to help with icon replacements
// Common icon mappings from Icons.* to MaterialSymbols

const Map<String, String> iconReplacements = {
  // Basic navigation
  'Icons.home_outlined': 'MaterialSymbols.home',
  'Icons.home': 'MaterialSymbols.homeFilled',
  'Icons.search': 'MaterialSymbols.search',
  'Icons.search_rounded': 'MaterialSymbols.search',
  'Icons.person_outline': 'MaterialSymbols.person',
  'Icons.person': 'MaterialSymbols.personFilled',
  'Icons.video_library_outlined': 'MaterialSymbols.library',
  'Icons.video_library': 'MaterialSymbols.libraryFilled',
  
  // Actions
  'Icons.favorite_border': 'MaterialSymbols.favorite',
  'Icons.favorite': 'MaterialSymbols.favoriteFilled',
  'Icons.favorite_rounded': 'MaterialSymbols.favoriteFilled',
  'Icons.bookmark_border': 'MaterialSymbols.bookmark',
  'Icons.bookmark': 'MaterialSymbols.bookmarkFilled',
  'Icons.bookmark_rounded': 'MaterialSymbols.bookmarkFilled',
  'Icons.share': 'MaterialSymbols.share',
  'Icons.share_rounded': 'MaterialSymbols.shareFilled',
  'Icons.download': 'MaterialSymbols.download',
  'Icons.download_rounded': 'MaterialSymbols.downloadFilled',
  'Icons.download_outlined': 'MaterialSymbols.download',
  'Icons.add': 'MaterialSymbols.add',
  'Icons.add_rounded': 'MaterialSymbols.addFilled',
  'Icons.star': 'MaterialSymbols.starFilled',
  'Icons.star_border': 'MaterialSymbols.star',
  
  // Media controls
  'Icons.play_arrow': 'MaterialSymbols.play',
  'Icons.play_arrow_rounded': 'MaterialSymbols.playFilled',
  'Icons.play_circle': 'MaterialSymbols.playFilled',
  'Icons.play_circle_outline': 'MaterialSymbols.play',
  'Icons.pause_circle': 'MaterialSymbols.pauseFilled',
  'Icons.pause_circle_outline': 'MaterialSymbols.pause',
  'Icons.stop_circle': 'MaterialSymbols.stopFilled',
  'Icons.stop_circle_outlined': 'MaterialSymbols.stop',
  'Icons.skip_next': 'MaterialSymbols.skipNextFilled',
  'Icons.skip_next_outlined': 'MaterialSymbols.skipNext',
  'Icons.skip_previous': 'MaterialSymbols.skipPreviousFilled',
  'Icons.skip_previous_outlined': 'MaterialSymbols.skipPrevious',
  
  // Content types
  'Icons.movie': 'MaterialSymbols.movieFilled',
  'Icons.movie_outlined': 'MaterialSymbols.movie',
  'Icons.tv': 'MaterialSymbols.tvFilled',
  'Icons.tv_outlined': 'MaterialSymbols.tv',
  'Icons.tv_rounded': 'MaterialSymbols.tvFilled',
  
  // Settings and info
  'Icons.settings': 'MaterialSymbols.settingsFilled',
  'Icons.settings_outlined': 'MaterialSymbols.settings',
  'Icons.info': 'MaterialSymbols.infoFilled',
  'Icons.info_outlined': 'MaterialSymbols.info',
  'Icons.info_outline_rounded': 'MaterialSymbols.info',
  'Icons.edit': 'MaterialSymbols.editFilled',
  'Icons.edit_outlined': 'MaterialSymbols.edit',
  'Icons.delete': 'MaterialSymbols.deleteFilled',
  'Icons.delete_outline': 'MaterialSymbols.delete',
  'Icons.more_vert': 'MaterialSymbols.moreVertFilled',
  'Icons.more_vert_outlined': 'MaterialSymbols.moreVert',
  'Icons.more_vert_rounded': 'MaterialSymbols.moreVertFilled',
  'Icons.more_horiz': 'MaterialSymbols.moreHorizFilled',
  'Icons.more_horiz_outlined': 'MaterialSymbols.moreHoriz',
  
  // Other common icons
  'Icons.clear': 'MaterialSymbols.delete',
  'Icons.close': 'MaterialSymbols.delete',
  'Icons.check': 'MaterialSymbols.checkFilled',
  'Icons.check_circle': 'MaterialSymbols.checkFilled',
  'Icons.check_circle_outline': 'MaterialSymbols.check',
  'Icons.arrow_back': 'MaterialSymbols.delete', // Close/back
  'Icons.refresh': 'MaterialSymbols.settings', // Refresh
  'Icons.fullscreen': 'MaterialSymbols.fullscreenFilled',
  'Icons.fullscreen_outlined': 'MaterialSymbols.fullscreen',
  'Icons.fullscreen_exit': 'MaterialSymbols.fullscreenExitFilled',
  'Icons.fullscreen_exit_outlined': 'MaterialSymbols.fullscreenExit',
  'Icons.notifications': 'MaterialSymbols.notificationsFilled',
  'Icons.notifications_outlined': 'MaterialSymbols.notifications',
  'Icons.notifications_off': 'MaterialSymbols.notificationsOffFilled',
  'Icons.notifications_off_outlined': 'MaterialSymbols.notificationsOff',
  'Icons.login': 'MaterialSymbols.person',
  'Icons.logout': 'MaterialSymbols.person',
  'Icons.person_add': 'MaterialSymbols.personFilled',
  'Icons.calendar_today': 'MaterialSymbols.calendarFilled',
  'Icons.calendar_today_outlined': 'MaterialSymbols.calendar',
  'Icons.schedule': 'MaterialSymbols.scheduleFilled',
  'Icons.schedule_outlined': 'MaterialSymbols.schedule',
  'Icons.folder': 'MaterialSymbols.folderFilled',
  'Icons.folder_outlined': 'MaterialSymbols.folder',
  'Icons.category': 'MaterialSymbols.categoryFilled',
  'Icons.category_outlined': 'MaterialSymbols.category',
  'Icons.grid_view': 'MaterialSymbols.category',
  'Icons.grid_view_rounded': 'MaterialSymbols.categoryFilled',
  'Icons.view_list': 'MaterialSymbols.category',
  'Icons.view_list_rounded': 'MaterialSymbols.categoryFilled',
  'Icons.view_module': 'MaterialSymbols.categoryFilled',
  'Icons.trending_up_rounded': 'MaterialSymbols.starFilled',
  'Icons.language': 'MaterialSymbols.settings',
  'Icons.translate': 'MaterialSymbols.settingsFilled',
  'Icons.color_lens': 'MaterialSymbols.settingsFilled',
  'Icons.speed': 'MaterialSymbols.settings',
  'Icons.aspect_ratio': 'MaterialSymbols.settings',
  'Icons.memory': 'MaterialSymbols.settings',
  'Icons.hd': 'MaterialSymbols.settings',
  'Icons.touch_app': 'MaterialSymbols.settings',
  'Icons.fast_forward': 'MaterialSymbols.skipNextFilled',
  'Icons.subtitles': 'MaterialSymbols.settings',
  'Icons.screen_rotation': 'MaterialSymbols.settings',
  'Icons.picture_in_picture': 'MaterialSymbols.settings',
  'Icons.picture_in_picture_alt': 'MaterialSymbols.settings',
  'Icons.volume_up': 'MaterialSymbols.volumeUpFilled',
  'Icons.volume_up_outlined': 'MaterialSymbols.volumeUp',
  'Icons.volume_off': 'MaterialSymbols.volumeOffFilled',
  'Icons.volume_off_outlined': 'MaterialSymbols.volumeOff',
  'Icons.download_for_offline_rounded': 'MaterialSymbols.downloadFilled',
};
