name: cinemer
description: A movie, TV shows & anime app powered by TMDB

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Internationalization
  flutter_localizations:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^7.0.7296
  material_symbols_icons: ^4.2780.0
  google_fonts: ^6.2.1
  flutter_staggered_grid_view: ^0.7.0
  
  # State Management
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Navigation
  go_router: ^14.0.0
  
  # Network & API
  http: ^1.1.2
  dio: ^5.4.0
  retrofit: ^4.0.3
  
  # Image Loading & Caching
  cached_network_image: ^3.3.0
  
  # Video Player
  video_player: ^2.9.1
  chewie: ^1.10.0
  youtube_explode_dart: ^2.2.0
  path_provider: ^2.1.2
  
  # File downloads and storage
  dio_smart_retry: ^6.0.0
  flutter_downloader: ^1.11.7
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.2
  connectivity_plus: ^5.0.2
  permission_handler: ^11.1.0
  
  # Animations & Loading
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # Theme & Design
  dynamic_color: ^1.6.8
  flex_color_scheme: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^4.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  
  # App Icon Generation
  flutter_launcher_icons: ^0.13.1
  
  # Splash Screen Generation  
  flutter_native_splash: ^2.3.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#F5F5F5"
    theme_color: "#1976D2"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"
  linux:
    generate: true
    image_path: "assets/icons/app_icon.png"
  
  # Adaptive icons for Android with Material You support
  adaptive_icon_background: "assets/icons/adaptive_background.png"
  adaptive_icon_foreground: "assets/icons/adaptive_foreground.png"
  adaptive_icon_monochrome: "assets/icons/adaptive_monochrome.png"

# Flutter Native Splash Configuration
flutter_native_splash:
  # Background color
  color: "#ffffff"
  
  # Splash screen image (using the same icon as the launcher)
  image: "assets/icons/app_icon.png"
  
  # Dark mode splash screen
  color_dark: "#121212"
  image_dark: "assets/icons/app_icon.png"
  
  # Android 12+ support with Material You theming
  android_12:
    image: "assets/icons/app_icon.png"
    color: "#ffffff"
    image_dark: "assets/icons/app_icon.png"
    color_dark: "#121212"

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
